### PR TITLE
Added 'me' query returning the currently logged in user. Closes #216.

### LINKED ISSUE #216: Query to identify the currently logged in user
## Description
As a CT user I would like to have a query that takes my login information and returns known information 

## Acceptance criteria

- [ ] New query e.g. whoami that returns a User

### PR DESCRIPTION
**Pull request by valentinyanakiev**
### Describe the background of your pull request

Added me query returning the currently logged in user.

### Additional context

To test it log in with the client and add the Bearer token as authorization header in the HTTP headers in GQL playground.

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [x] I've read the contributing document https://github.com/cherrytwist/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/cherrytwist/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/cherrytwist/Coordination/blob/master/LICENSE 
     and the contributor license agreement: tba

### CODE REVIEW

**Comment by techsmyth** [comment]
Was not able to get this working:
- What is the name of the bearer header and where can I locate the token to put in there?
- It looks like the whole context is being logged to the console
- Tried putting the same auth guard around another query that is used by the client (so header presumably is set?) - challenges() - and got the following error:

===
{"name":"AzureAD: Bearer Strategy","hostname":"Spectre360v2","pid":7888,"level":30,"msg":"In Strategy.prototype.authenticate: we will validate the following options: {\"issuer\":[\"https://login.microsoftonline.com/524e761c-d162-4fdf-ab43-2855246d986c/v2.0\"],\"algorithms\":[\"RS256\"],\"audience\":[\"505041fc-fca2-4a74-88ee-6d50a6417e38\"],\"validateIssuer\":true,\"allowMultiAudiencesInToken\":false,\"clockSkew\":300,\"scope\":[\"Cherrytwist-GraphQL\"],\"isAccessToken\":true}","time":"2020-10-17T10:45:39.441Z","v":0}
{"name":"AzureAD: Bearer Strategy","hostname":"Spectre360v2","pid":7888,"level":30,"msg":"authentication failed due to: token is not found","time":"2020-10-17T10:45:39.444Z","v":0}
[Nest] 7888   - 10/17/2020, 12:45:39   [ExceptionsHandler] GqlAuthGuard +14676ms
AuthenticationError: GqlAuthGuard
    at GqlAuthGuard.handleRequest (C:\Users\neil\Documents\Dev_CT\Server\src\utils\authentication\graphql.guard.ts:19:20)

=====

**Review by techsmyth — COMMENTED** [review]
See comment added

**Comment by valentinyanakiev** [comment]
> Was not able to get this working:
> 
> * What is the name of the bearer header and where can I locate the token to put in there?
> * It looks like the whole context is being logged to the console
> * Tried putting the same auth guard around another query that is used by the client (so header presumably is set?) - challenges() - and got the following error:
> 
> ===
> {"name":"AzureAD: Bearer Strategy","hostname":"Spectre360v2","pid":7888,"level":30,"msg":"In Strategy.prototype.authenticate: we will validate the following options: {"issuer":["https://login.microsoftonline.com/524e761c-d162-4fdf-ab43-2855246d986c/v2.0"],"algorithms":["RS256"],"audience":["505041fc-fca2-4a74-88ee-6d50a6417e38"],"validateIssuer":true,"allowMultiAudiencesInToken":false,"clockSkew":300,"scope":["Cherrytwist-GraphQL"],"isAccessToken":true}","time":"2020-10-17T10:45:39.441Z","v":0}
> {"name":"AzureAD: Bearer Strategy","hostname":"Spectre360v2","pid":7888,"level":30,"msg":"authentication failed due to: token is not found","time":"2020-10-17T10:45:39.444Z","v":0}
> [Nest] 7888 - 10/17/2020, 12:45:39 [ExceptionsHandler] GqlAuthGuard +14676ms
> AuthenticationError: GqlAuthGuard
> at GqlAuthGuard.handleRequest (C:\Users\neil\Documents\Dev_CT\Server\src\utils\authentication\graphql.guard.ts:19:20)
> 
> =====

Look at the additional context - add the bearer token to the authorization header in the HTTP headers in GQL playground to test it. Such as (this token expired so can't be used, just as a sample): 
{
  "authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImtnMkxZczJUMENUaklmajRydDZKSXluZW4zOCJ9.eyJhdWQiOiI1MDUwNDFmYy1mY2EyLTRhNzQtODhlZS02ZDUwYTY0MTdlMzgiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vNTI0ZTc2MWMtZDE2Mi00ZmRmLWFiNDMtMjg1NTI0NmQ5ODZjL3YyLjAiLCJpYXQiOjE2MDI4NjUwNTYsIm5iZiI6MTYwMjg2NTA1NiwiZXhwIjoxNjAyODY4OTU2LCJhaW8iOiJBVFFBeS84UkFBQUFtcW1DR1NRbkpKTVI3ODBGdUF0ODNET3FQN2lPOGw1Mzk5QzNQTDF0NlJFaHVRZ1psWFhWWTVLS1hZNzJUcFlwIiwiYXpwIjoiZmViNmQ4YjEtOGNjMi00ZTdkLWE0MTktYWQ3YjU0NGIwODMyIiwiYXpwYWNyIjoiMCIsImVtYWlsIjoiYWRtaW5AY2hlcnJ5dHdpc3Qub3JnIiwibmFtZSI6IkFkbWluIiwib2lkIjoiNGQ4Y2JmNjUtMWRjMi00MGY2LThlZGUtNzNmNWI5MGE2Njk1IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW5AcGxheWdyb3VuZGNoZXJyeXR3aXN0Lm9ubWljcm9zb2Z0LmNvbSIsInJoIjoiMC5BQUFBSEhaT1VtTFIzMC1yUXloVkpHMlliTEhZdHY3Q2pIMU9wQm10ZTFSTENESjBBQkkuIiwic2NwIjoiQ2hlcnJ5dHdpc3QtR3JhcGhRTCIsInN1YiI6IjlRYWx1aXFrdTg2VU5RdzFXT3ZOazh0bWdpQ0J3T2VqRk1yMlJ6QnBPZVUiLCJ0aWQiOiI1MjRlNzYxYy1kMTYyLTRmZGYtYWI0My0yODU1MjQ2ZDk4NmMiLCJ1dGkiOiJPT05ubXdwSlFrU3hyMnFBdkFWWkFBIiwidmVyIjoiMi4wIn0.BnX1VLtSds3njzVBQHFjns2QUdb9GpiFYXwA9mzIxlPBJCC8YyfQ9_zbPG4o0OqmAzjjBeb9G_YNdPl1BZEEt8lJoGUvh-RRYpSA3aDC0O2F2hxWA_lJW-ypjh4y9iQKF13qFdk2H2cf8BhRbAeN7JjcpLrxPIRokyasuLcCOUon5HhmVX4mIsB5sp-Oc4O5BY0cwTWGJt0iLYdmvkWZGPUWaQgZr_UM246kf9WAhO-OGoTibQERPrSTND8YxUq9WiOK-kiezyYQ7-HSTvk8Dk8bAtMGga_WUAIOBcP-rqhIz1RxCLmCZTh0sGi7ETZuQnT8KpGkX4sb2fU6uRXRpg"
}

You can get the token when you log in the client. The token is logged to the console. About the auth headers added to the requests to the server - I am not sure this is added. I consider it part of the authorisation (it should be straightforward thou). I just looked at the request headers in the network tab sending one request - Authorization header is not added to the requests of the client.

**Comment by techsmyth** [comment]
Just tried again...got the code from the client console: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImtnMkxZczJUMENUaklmajRydDZKSXluZW4zOCJ9.eyJhdWQiOiI1MDUwNDFmYy1mY2EyLTRhNzQtODhlZS02ZDUwYTY0MTdlMzgiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vNTI0ZTc2MWMtZDE2Mi00ZmRmLWFiNDMtMjg1NTI0NmQ5ODZjL3YyLjAiLCJpYXQiOjE2MDMwMDA1NzUsIm5iZiI6MTYwMzAwMDU3NSwiZXhwIjoxNjAzMDA0NDc1LCJhaW8iOiJBWVFBZS84UkFBQUFqV042YS9QdkF5b0J1c003M2ViaFJ0UUVsbktQZ2JvcFBRTHo1K1dVcmJYNUJ6dnd6UThuT2svOSt3Mzh1NXZsNkJKc0k5OXIzdEttaHNvMjB2dmpBT3hZNE5nbEJNOCtleWtmMkhzMmlYY0hlaktCNjl4aDJqWlRuRkxYNWFwbkJYN1kxVWJIR2psRmpGcXV0ODNQb3BPbzFuaGpMeUdzR0FabmJNekF2azA9IiwiYXpwIjoiZmViNmQ4YjEtOGNjMi00ZTdkLWE0MTktYWQ3YjU0NGIwODMyIiwiYXpwYWNyIjoiMCIsImVtYWlsIjoibmVpbEBjaGVycnl0d2lzdC5vcmciLCJpZHAiOiJsaXZlLmNvbSIsIm5hbWUiOiJOZWlsIFNteXRoIiwib2lkIjoiMDE4NzJkNmItNmY3YS00OGUwLThjNGYtZDkwNWU5MjQ1NDUxIiwicHJlZmVycmVkX3VzZXJuYW1lIjoibmVpbEBjaGVycnl0d2lzdC5vcmciLCJyaCI6IjAuQUFBQUhIWk9VbUxSMzAtclF5aFZKRzJZYkxIWXR2N0NqSDFPcEJtdGUxUkxDREowQURvLiIsInNjcCI6IkNoZXJyeXR3aXN0LUdyYXBoUUwiLCJzdWIiOiJ3WnNIakJqLWN3bWlTS1l6TjRMYWZHY1JiVjJDeE0tcGZwdUlielJrdXdBIiwidGlkIjoiNTI0ZTc2MWMtZDE2Mi00ZmRmLWFiNDMtMjg1NTI0NmQ5ODZjIiwidXRpIjoiZnpwVHhvclRGRVNld3JlWUlKSlBBQSIsInZlciI6IjIuMCJ9.Z0GJk2vKe1QA5G4GAn9yb4F49aNke8W7PpiSN8j626SGefNFfTDndtm5O8K8YqmIqqNxplaMh8BsOnCV17kAjn649LbLt79nGmuHeei57dGZzzX6_No7H7Rd1pX925tIRHxk40ZhsLcsueJwKL2XicYyKzMADIZ269LXG9jUH8L435y3ECmti-osScgvlzUVcyZOjlVVXUIGl6EJxAnV7dAyh-I2QHTSdSDQJU36hrW8DWlxJfg5h0sMedYysq1e0UpuVISHilpSwwI4P8iF49YUey82gmGgdk3Ik8fAwko_wnUrcoIGsCrawTqFE_qDF1UAkxoyB30cJuHmtLwAeg

Added it into the header: 
image

Error on server:
{"name":"AzureAD: Bearer Strategy","hostname":"Spectre360v2","pid":19832,"level":30,"msg":"In Strategy.prototype.authenticate: received access_token from request header: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImtnMkxZczJUMENUaklmajRydDZKSXluZW4zOCJ9.eyJhdWQiOiI1MDUwNDFmYy1mY2EyLTRhNzQtODhlZS02ZDUwYTY0MTdlMzgiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vNTI0ZTc2MWMtZDE2Mi00ZmRmLWFiNDMtMjg1NTI0NmQ5ODZjL3YyLjAiLCJpYXQiOjE2MDMwMDA1NzUsIm5iZiI6MTYwMzAwMDU3NSwiZXhwIjoxNjAzMDA0NDc1LCJhaW8iOiJBWVFBZS84UkFBQUFqV042YS9QdkF5b0J1c003M2ViaFJ0UUVsbktQZ2JvcFBRTHo1K1dVcmJYNUJ6dnd6UThuT2svOSt3Mzh1NXZsNkJKc0k5OXIzdEttaHNvMjB2dmpBT3hZNE5nbEJNOCtleWtmMkhzMmlYY0hlaktCNjl4aDJqWlRuRkxYNWFwbkJYN1kxVWJIR2psRmpGcXV0ODNQb3BPbzFuaGpMeUdzR0FabmJNekF2azA9IiwiYXpwIjoiZmViNmQ4YjEtOGNjMi00ZTdkLWE0MTktYWQ3YjU0NGIwODMyIiwiYXpwYWNyIjoiMCIsImVtYWlsIjoibmVpbEBjaGVycnl0d2lzdC5vcmciLCJpZHAiOiJsaXZlLmNvbSIsIm5hbWUiOiJOZWlsIFNteXRoIiwib2lkIjoiMDE4NzJkNmItNmY3YS00OGUwLThjNGYtZDkwNWU5MjQ1NDUxIiwicHJlZmVycmVkX3VzZXJuYW1lIjoibmVpbEBjaGVycnl0d2lzdC5vcmciLCJyaCI6IjAuQUFBQUhIWk9VbUxSMzAtclF5aFZKRzJZYkxIWXR2N0NqSDFPcEJtdGUxUkxDREowQURvLiIsInNjcCI6IkNoZXJyeXR3aXN0LUdyYXBoUUwiLCJzdWIiOiJ3WnNIakJqLWN3bWlTS1l6TjRMYWZHY1JiVjJDeE0tcGZwdUlielJrdXdBIiwidGlkIjoiNTI0ZTc2MWMtZDE2Mi00ZmRmLWFiNDMtMjg1NTI0NmQ5ODZjIiwidXRpIjoiZnpwVHhvclRGRVNld3JlWUlKSlBBQSIsInZlciI6IjIuMCJ9.Z0GJk2vKe1QA5G4GAn9yb4F49aNke8W7PpiSN8j626SGefNFfTDndtm5O8K8YqmIqqNxplaMh8BsOnCV17kAjn649LbLt79nGmuHeei57dGZzzX6_No7H7Rd1pX925tIRHxk40ZhsLcsueJwKL2XicYyKzMADIZ269LXG9jUH8L435y3ECmti-osScgvlzUVcyZOjlVVXUIGl6EJxAnV7dAyh-I2QHTSdSDQJU36hrW8DWlxJfg5h0sMedYysq1e0UpuVISHilpSwwI4P8iF49YUey82gmGgdk3Ik8fAwko_wnUrcoIGsCrawTqFE_qDF1UAkxoyB30cJuHmtLwAeg","time":"2020-10-18T06:01:43.710Z","v":0}
{"name":"AzureAD: Bearer Strategy","hostname":"Spectre360v2","pid":19832,"level":30,"msg":"In Strategy.prototype.jwtVerify: token decoded:   {\n  header: { typ: 'JWT', alg: 'RS256', kid: 'kg2LYs2T0CTjIfj4rt6JIynen38' },\n  payload: {\n    aud: '505041fc-fca2-4a74-88ee-6d50a6417e38',\n    iss: 'https://login.microsoftonline.com/524e761c-d162-4fdf-ab43-2855246d986c/v2.0',\n    iat: 1603000575,\n    nbf: 1603000575,\n    exp: 1603004475,\n    aio: 'AYQAe/8RAAAAjWN6a/PvAyoBusM73ebhRtQElnKPgbopPQLz5+WUrbX5BzvwzQ8nOk/9+w38u5vl6BJsI99r3tKmhso20vvjAOxY4NglBM8+eykf2Hs2iXcHejKB69xh2jZTnFLX5apnBX7Y1UbHGjlFjFqut83PopOo1nhjLyGsGAZnbMzAvk0=',\n    azp: 'feb6d8b1-8cc2-4e7d-a419-ad7b544b0832',\n    azpacr: '0',\n    email: 'neil@cherrytwist.org',\n    idp: 'live.com',\n    name: 'Neil Smyth',\n    oid: '01872d6b-6f7a-48e0-8c4f-d905e9245451',\n    preferred_username: 'neil@cherrytwist.org',\n    rh: '0.AAAAHHZOUmLR30-rQyhVJG2YbLHYtv7CjH1OpBmte1RLCDJ0ADo.',\n    scp: 'Cherrytwist-GraphQL',\n    sub: 'wZsHjBj-cwmiSKYzN4LafGcRbV2CxM-pfpuIbzRkuwA',\n    tid: '524e761c-d162-4fdf-ab43-2855246d986c',\n    uti: 'fzpTxorTFESewreYIJJPAA',\n    ver: '2.0'\n  },\n  signature: 'Z0GJk2vKe1QA5G4GAn9yb4F49aNke8W7PpiSN8j626SGefNFfTDndtm5O8K8YqmIqqNxplaMh8BsOnCV17kAjn649LbLt79nGmuHeei57dGZzzX6_No7H7Rd1pX925tIRHxk40ZhsLcsueJwKL2XicYyKzMADIZ269LXG9jUH8L435y3ECmti-osScgvlzUVcyZOjlVVXUIGl6EJxAnV7dAyh-I2QHTSdSDQJU36hrW8DWlxJfg5h0sMedYysq1e0UpuVISHilpSwwI4P8iF49YUey82gmGgdk3Ik8fAwko_wnUrcoIGsCrawTqFE_qDF1UAkxoyB30cJuHmtLwAeg'\n}","time":"2020-10-18T06:01:43.716Z","v":0}
{"name":"AzureAD: Metadata Parser","hostname":"Spectre360v2","pid":19832,"level":30,"msg":"working on key: {\n  kty: 'RSA',\n  use: 'sig',\n  kid: 'kg2LYs2T0CTjIfj4rt6JIynen38',\n  x5t: 'kg2LYs2T0CTjIfj4rt6JIynen38',\n  n: 'yTKa6m5GFOllz7oIHFCkvRJoBv7wLMuKIPLHbFGh5yOiO8o3akoqMhf1x6MxINGhZo6dkIrhVlVfWJhEJZPVaQdvyvVmlIZruhcbz3PGMqPAbjq2JqbB1mMnsyGHx-ovP0Cm5xj8sgI8wm67p3nosqzqFvg6mPKVO-w1QBr5seDU2AwU2DR88LF2v03Zjgn4mGvPdUOXihTQoNlf-nJFduXMDyRgZabnR2HlYHhagHwy1beWW1WtEaPz8iBN_0bGkGw705aDBUHJkdTty1mzsCZRur_n0imqXu9IzoSyiq5d0yKrRA5xkA-K3DMeRMquZ5QvPT9Eee4EZfFL97zBfQ',\n  e: 'AQAB',\n  x5c: [\n    'MIIDBTCCAe2gAwIBAgIQQiR8gZNKuYpH6cP+KIE5ijANBgkqhkiG9w0BAQsFADAtMSswKQYDVQQDEyJhY2NvdW50cy5hY2Nlc3Njb250cm9sLndpbmRvd3MubmV0MB4XDTIwMDgyODAwMDAwMFoXDTI1MDgyODAwMDAwMFowLTErMCkGA1UEAxMiYWNjb3VudHMuYWNjZXNzY29udHJvbC53aW5kb3dzLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMkymupuRhTpZc+6CBxQpL0SaAb+8CzLiiDyx2xRoecjojvKN2pKKjIX9cejMSDRoWaOnZCK4VZVX1iYRCWT1WkHb8r1ZpSGa7oXG89zxjKjwG46tiamwdZjJ7Mhh8fqLz9ApucY/LICPMJuu6d56LKs6hb4OpjylTvsNUAa+bHg1NgMFNg0fPCxdr9N2Y4J+Jhrz3VDl4oU0KDZX/pyRXblzA8kYGWm50dh5WB4WoB8MtW3lltVrRGj8/IgTf9GxpBsO9OWgwVByZHU7ctZs7AmUbq/59Ipql7vSM6EsoquXdMiq0QOcZAPitwzHkTKrmeULz0/RHnuBGXxS/e8wX0CAwEAAaMhMB8wHQYDVR0OBBYEFGcWXwaqmO25Blh2kHHAFrM/AS2CMA0GCSqGSIb3DQEBCwUAA4IBAQDFnKQ98CBnvVd4OhZP0KpaKbyDv93PGukE1ifWilFlWhvDde2mMv/ysBCWAR8AGSb1pAW/ZaJlMvqSN/+dXihcHzLEfKbCPw4/Mf2ikq4gqigt5t6hcTOSxL8wpe8OKkbNCMcU0cGpX5NJoqhJBt9SjoD3VPq7qRmDHX4h4nniKUMI7awI94iGtX/vlHnAMU4+8y6sfRQDGiCIWPSyypIWfEA6/O+SsEQ7vZ/b4mXlghUmxL+o2emsCI1e9PORvm5yc9Y/htN3Ju0x6ElHnih7MJT6/YUMISuyob9/mbw8Vf49M7H2t3AE5QIYcjqTwWJcwMlq5i9XfW2QLGH7K5i8'\n  ],\n  issuer: 'https://login.microsoftonline.com/524e761c-d162-4fdf-ab43-2855246d986c/v2.0'\n}","time":"2020-10-18T06:01:43.769Z","v":0}
{"name":"AzureAD: Bearer Strategy","hostname":"Spectre360v2","pid":19832,"level":30,"msg":"PEMkey generated: -----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEAyTKa6m5GFOllz7oIHFCkvRJoBv7wLMuKIPLHbFGh5yOiO8o3akoq\nMhf1x6MxINGhZo6dkIrhVlVfWJhEJZPVaQdvyvVmlIZruhcbz3PGMqPAbjq2JqbB\n1mMnsyGHx+ovP0Cm5xj8sgI8wm67p3nosqzqFvg6mPKVO+w1QBr5seDU2AwU2DR8\n8LF2v03Zjgn4mGvPdUOXihTQoNlf+nJFduXMDyRgZabnR2HlYHhagHwy1beWW1Wt\nEaPz8iBN/0bGkGw705aDBUHJkdTty1mzsCZRur/n0imqXu9IzoSyiq5d0yKrRA5x\nkA+K3DMeRMquZ5QvPT9Eee4EZfFL97zBfQIDAQAB\n-----END RSA PUBLIC KEY-----\n","time":"2020-10-18T06:01:43.816Z","v":0}
{"name":"AzureAD: Bearer Strategy","hostname":"Spectre360v2","pid":19832,"level":30,"msg":"In Strategy.prototype.jwtVerify: VerifiedToken:  {\n  aud: '505041fc-fca2-4a74-88ee-6d50a6417e38',\n  iss: 'https://login.microsoftonline.com/524e761c-d162-4fdf-ab43-2855246d986c/v2.0',\n  iat: 1603000575,\n  nbf: 1603000575,\n  exp: 1603004475,\n  aio: 'AYQAe/8RAAAAjWN6a/PvAyoBusM73ebhRtQElnKPgbopPQLz5+WUrbX5BzvwzQ8nOk/9+w38u5vl6BJsI99r3tKmhso20vvjAOxY4NglBM8+eykf2Hs2iXcHejKB69xh2jZTnFLX5apnBX7Y1UbHGjlFjFqut83PopOo1nhjLyGsGAZnbMzAvk0=',\n  azp: 'feb6d8b1-8cc2-4e7d-a419-ad7b544b0832',\n  azpacr: '0',\n  email: 'neil@cherrytwist.org',\n  idp: 'live.com',\n  name: 'Neil Smyth',\n  oid: '01872d6b-6f7a-48e0-8c4f-d905e9245451',\n  preferred_username: 'neil@cherrytwist.org',\n  rh: '0.AAAAHHZOUmLR30-rQyhVJG2YbLHYtv7CjH1OpBmte1RLCDJ0ADo.',\n  scp: 'Cherrytwist-GraphQL',\n  sub: 'wZsHjBj-cwmiSKYzN4LafGcRbV2CxM-pfpuIbzRkuwA',\n  tid: '524e761c-d162-4fdf-ab43-2855246d986c',\n  uti: 'fzpTxorTFESewreYIJJPAA',\n  ver: '2.0'\n}","time":"2020-10-18T06:01:43.819Z","v":0}
{"name":"AzureAD: Bearer Strategy","hostname":"Spectre360v2","pid":19832,"level":30,"msg":"In Strategy.prototype.jwtVerify: We did pass Req back to Callback","time":"2020-10-18T06:01:43.868Z","v":0}
Failed adding the user to the request object: Error: Unauthorized
{"name":"AzureAD: Bearer Strategy","hostname":"Spectre360v2","pid":19832,"level":30,"msg":"authentication failed due to: error: invalid_token","time":"2020-10-18T06:01:43.925Z","v":0}
[Nest] 19832   - 10/18/2020, 08:01:43   [ExceptionsHandler] Failed adding the user to the request object: Error: Unauthorized +126713ms
Error: Failed adding the user to the request object: Error: Unauthorized
    at AzureADStrategy.validate (C:\Users\neil\Documents\Dev_CT\Server\dist\utils\authentication\aad.strategy.js:48:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Review by techsmyth — APPROVED** [review]
Working - was missing a user with my email address on the server

**Pull request merged**
